"""
NetCDF utility function to save a numpy array as a NetCDF file with projection and meta data.
"""

# pylint: disable=W0212, W0718,R0915,E1101,R0914

import datetime
import numpy as np
import hf_hydrodata as hf
import xarray as xr
import pyproj

def generate_netcdf_file(
    data: np.ndarray, entry: dict, query_parameters: dict, file_path: str, include_coords=True
):
    """Generate a NetCDF file from numpy data array."""

    grid = entry.get("grid")
    grid_bounds = hf.gridded._get_grid_bounds(grid, query_parameters)
    variable = entry.get("variable")
    dataset = entry.get("dataset")
    temporal_resolution = entry.get("temporal_resolution")

    metadata = construct_metadata(entry, query_parameters)

    if len(data.shape) == 3:
        nx = data.shape[2]
        ny = data.shape[1]
    elif len(data.shape) == 2:
        nx = data.shape[1]
        ny = data.shape[0]
    else:
        raise ValueError("Data shape has too many dimensions")

    grid_data = hf.get_table_row("grid", id=grid)
    proj4_str = grid_data.get("crs")
    dx = float(grid_data.get("resolution_meters"))
    dy = float(grid_data.get("resolution_meters"))

    # Create x,y Dimensions
    x0 = float(grid_data.get("origin")[0])
    y0 = float(grid_data.get("origin")[1])
    if grid_bounds and len(grid_bounds) == 4:
        left_origin = x0 + grid_bounds[0] * dx
        bottom_origin = y0 + grid_bounds[1] * dx
    else:
        # If there no grid_bounds then the origin is the same as origin of the grid itself
        left_origin = x0
        bottom_origin = y0

    x = left_origin + (np.arange(nx) + 0.5) * dx
    y = bottom_origin + (np.arange(ny) + 0.5 * 0) * dy

    wkt = pyproj.CRS.from_proj4(proj4_str).to_wkt()

    coords = {}
    data_vars = {}

    dimension_names = add_time_coordinate(
        coords, data, temporal_resolution, query_parameters
    )
    coords["y"] = ("y", y, {"units": "m", "standard_name": "projection_y_coordinate", "long_name": "y coordinate of projection", "axis": "Y"})
    coords["x"] = ("x", x, {"units": "m", "standard_name": "projection_x_coordinate", "long_name": "x coordinate of projection", "axis": "X"})
    data_vars[variable] = (
        dimension_names,
        data,
        {
            "long_name": variable,
            "units": f"{dx} meters",
            "grid_mapping": "crs"
        },
    )
    ds = xr.Dataset(data_vars=data_vars, coords=coords)

    ds["crs"] = xr.DataArray(
        np.int32(-2147483647),
        attrs={
            "grid_mapping_name": "lambert_conformal_conic",
            "spatial_ref": wkt
        }
    )

    ds.attrs["title"] = f"{variable} from dataset {dataset}"
    ds.attrs["Conventions"] = "CF-1.9"
    ds.attrs["source"] = "Generated by hf_hydrodata"
    for key in metadata:
        value = metadata.get(key)
        ds.attrs[key] = value

    ds.to_netcdf(file_path)

def add_time_coordinate(
    coords: dict,
    data: np.ndarray,
    temporal_resolution: str,
    query_parameters: dict,
):
    """
    Add a time coordinate to the data_vars if query has time dimension.
    Returns:
        An array of dimensions. Either ["time", "y", "x"] or ["y", "x"]
    """

    if temporal_resolution in ["daily", "hourly", "monthly", "weekly"]:
        date_start_str = get_date_start(query_parameters)
        date_start = datetime.datetime.strptime(date_start_str, "%Y-%m-%d")
        time_steps = data.shape[0]

        dates = []
        if temporal_resolution == "daily":
            delta = datetime.timedelta(days=1)
        elif temporal_resolution == "hourly":
            delta = datetime.timedelta(hours=1)
        elif temporal_resolution == "weekly":
            delta = datetime.timedelta(weeks=1)
        elif temporal_resolution == "monthly":
            delta = datetime.timedelta(months=1)
        dt = date_start
        for _ in range(0, time_steps):
            dates.append(dt)
            dt = dt + delta
        coords["time"] = ("time", dates)
        return ("time", "y", "x")
    else:
        return ("y", "x")


def construct_metadata(entry: dict, query_parameters: dict):
    """
    Constructs metadata for the generated NetCDF file from the entry and query_parameters.

    Parameters
    ----------
    entry : dict
        dictionary containg the data catalog entry.
    query_parameters : dict
        dictionary containg all query parameters in the request.

    Returns
    -------
    metadata : dict
        The metadata of the requested data for use in generated NetCDF file.
    """

    required_fields = [
        "dataset",
        "variable",
        "dataset_var",
        "temporal_resolution",
        "units",
        "aggregation",
        "grid",
        "documentation_notes",
        "description",
        "paper_dois",
        "dataset_dois",
        "dataset_start_date",
        "dataset_dnd_Date",
        "time_zone",
        "documentation_link",
    ]
    metadata = {
        key: value
        for key, value in entry.row_values.items()
        if key in required_fields and value
    }

    date_start =get_date_start(query_parameters)
    date_end = get_date_end(query_parameters)

    if date_start is None:
        date_start = "static"

    metadata.update({"entry_start_date": date_start})

    if date_end is None:
        metadata.update({"entry_end_date": date_start})
    else:
        metadata.update({"entry_end_date": date_end})

    return metadata

def get_date_start(options):
    """
    Get the date_start option from the options dict.
    This gets either start_time or date_start to be backward compatible with old names.

    Parameters:
        options:    A dict containing parameters to get_gridded_data.

    Returns:
        The value of the options as either a string or a datetime object from the dict.
    """
    result = options.get("date_start", None)
    result = options.get("start_date", None) if result is None else result
    result = options.get("start_time", None) if result is None else result
    return result


def get_date_end(options):
    """
    Get the date_end option from the options dict.
    This gets either end_time or date_end to be backward compatible with old names.

    Parameters:
        options:    A dict containing parameters to get_gridded_data.

    Returns:
        The value of the options as either a string or a datetime object from the dict.
    """
    result = options.get("date_end", None)
    result = options.get("end_date", None) if result is None else result
    result = options.get("end_time", None) if result is None else result
    return result

